name: Deploy Aleo Notarization Backend - Prod

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST_KEY_PROD }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      - name: Generate Ansible inventory
        env:
          HOSTS: ${{ secrets.PROD_SSH_HOSTS }}
        run: |
          mkdir -p deployment/ansible
          echo "[aleo_backend]" > deployment/ansible/inventory.ini
          i=1
          IFS=',' read -ra ADDR <<< "$HOSTS"
          for ip in "${ADDR[@]}"; do
            echo "backend-$i ansible_host=$ip" >> deployment/ansible/inventory.ini
            ((i++))
          done
          echo "[aleo_backend:vars]" >> deployment/ansible/inventory.ini
          echo "ansible_user=azureuser" >> deployment/ansible/inventory.ini
          echo "ansible_ssh_private_key_file=~/.ssh/id_rsa" >> deployment/ansible/inventory.ini
          echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> deployment/ansible/inventory.ini

          echo "âœ… Generated inventory:"
          # cat deployment/ansible/inventory.ini

      - name: Run Ansible playbook
        env:
          APP: ${{ vars.APP }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ansible-playbook deployment/ansible/deploy-aleo-notarization-be.yaml -i deployment/ansible/inventory.ini

      - name: Changelog
        id: Changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Prerelease ${{ github.ref }}
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload all enclave artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./enclave_artifacts-backend-1/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
